# Generated by Django 5.2 on 2025-04-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_categories_table_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='mentor',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
