# Generated by Django 5.2 on 2025-04-13 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courses_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='description',
        ),
    ]
